
<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class signa_model extends CI_Model
{

    public $table = 'signa';
    public $id = 'signa_id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
    $this->db->like('signa_id', $q);
    $this->db->or_like('signa_kode', $q);
	$this->db->or_like('signa_nama', $q);
    $this->db->or_like('additional_data', $q);
    $this->db->or_like('created_date', $q);
    $this->db->or_like('created_by', $q);
    $this->db->or_like('modified_count', $q);
    $this->db->or_like('last_modified_date', $q);
    $this->db->or_like('last_modified_by', $q);
    $this->db->or_like('is_deleted', $q);
    $this->db->or_like('is_active', $q);
    $this->db->or_like('deleted_date', $q);
    $this->db->or_like('deleted_by', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
    $this->db->like('signa_id', $q);
    $this->db->or_like('signa_kode', $q);
    $this->db->or_like('signa_nama', $q);
    $this->db->or_like('additional_data', $q);
    $this->db->or_like('created_date', $q);
    $this->db->or_like('created_by', $q);
    $this->db->or_like('modified_count', $q);
    $this->db->or_like('last_modified_date', $q);
    $this->db->or_like('last_modified_by', $q);
    $this->db->or_like('is_deleted', $q);
    $this->db->or_like('is_active', $q);
    $this->db->or_like('deleted_date', $q);
    $this->db->or_like('deleted_by', $q);;
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Merk_barang_model.php */
/* Location: ./application/models/Merk_barang_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-03 15:15:33 */
/* http://harviacode.com */